name: Jekyll Daily

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '55 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Jekyll Action
      uses: helaili/jekyll-action@1.0
